#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { execSync } from "child_process";

const root = process.cwd();
const outDir = path.join(root, "ops", "meetings", "generated");
const type = process.env.MEETING_TYPE || "daily";
const date = new Date().toISOString();

function safeExec(cmd) {
  try {
    return execSync(cmd, { stdio: ["ignore", "pipe", "ignore"] }).toString().trim();
  } catch {
    return "";
  }
}

const latestCommits = safeExec("git log -8 --oneline");
const changedFiles = safeExec("git diff --name-only HEAD~1..HEAD");

const content = `# AI Meeting Brief (${type})

GeneratedAt: ${date}

## Executive summary

- Autogenerated meeting brief for AI team review.

## Progress by role

- ChiefEngineer: release coordination and risk tracking.
- BlockchainEngineer: contract lane status from CI.
- FullstackEngineer: backend/frontend delivery status.
- QAEngineer: validation status and blockers.
- MarketingLead: channel campaign and publishing summary.
- DesignLead: creative output and pending assets.

## Recent commits

\`\`\`
${latestCommits || "No recent commits found."}
\`\`\`

## Recently changed files

\`\`\`
${changedFiles || "No changed files in last window."}
\`\`\`

## Risks and blockers

- Add manual notes for incidents, failed checks, or degraded services.

## Decisions needed

- Confirm next release scope.
- Confirm channel priorities for current campaign.

## Next actions

- [ ] Assign owners and ETAs for top 3 priorities.
- [ ] Confirm production readiness status.
- [ ] Confirm rollback and incident owner on duty.
`;

fs.mkdirSync(outDir, { recursive: true });
const output = path.join(outDir, `brief-${type}-${new Date().toISOString().slice(0, 10)}.md`);
fs.writeFileSync(output, content, "utf8");
console.log(`Meeting brief generated: ${output}`);
